### ISSUE TITLE
Slack Notifier & Singleton ? 

### ISSUE THREAD

**Issue by Vialonyx** [stevenosloan/slack-notifier#101]
Hi, 
Is it possible to use this gem with a singleton ? 
It would be easier than creating an instance each time. 

Thanks.

**Comment by stevenosloan** [comment]
Not direclty on the Slack::Notifier class, I can't think of a reason storing it elsewhere would be problematic. You could create a const to act as one (or store in on an app instance, etc)

```ruby
NOTIFIER = Slack::Notifier.new "WEBHOOK_URL"
NOTIFIER.post text: "Hello"
```

Depending on your use case there may be a more applicable, nuanced solution ([there are a few good ones here](https://dalibornasevic.com/posts/9-ruby-singleton-pattern) if you're looking for some alternatives).

**Comment by Vialonyx** [comment]
Thank you for your prompt response.
I will use one of these solutions.
