### ISSUE TITLE
Does this gem support Slack's new 'block' message format?

### ISSUE THREAD

**Issue by rnhurt** [stevenosloan/slack-notifier#109]
Slack recently (early 2019) introduced [block messaging formats](https://api.slack.com/messaging/attachments-to-blocks).  I've tried to use the normal workflow with this Gem but it doesn't seem to handle it properly.  Is there some option that I don't know about or does this Gem need to be updated to handle this new functionality?

**Comment by rnhurt** [comment]
I was incorrect in my earlier assumption; this Gem can use the new functionality without any changes.  Instead of posting `attachments`
```ruby
message = { ... my legacy message goes here ... }
notifier.post attachments: [attachment]
```

you just have to post `blocks`
```ruby
message = { ... my block message goes here ... }
notifier.post blocks: [message]
```

**Comment by georgemabey** [comment]
@rnhurt What format should `message` be to get blocks to work?

I'm currently sending this JSON in the `message` parameter, but it's saying the blocks are invalid:


```
{
  "blocks":[
    {"type":"section","text":{"type":"mrkdwn","text":"*Bets placed:*"}},
    {"type":"divider"},
    {
      "type":"section",
      "text":{
        "type":"mrkdwn",
        "text":"*Newcastle vs Brighton*\n*Back:* Newcastle\n *Stake:* 10\n*Status:* SUCCESS\n*Error message:* ERROR\n"
      },
      "accessory":{
        "type":"button",
        "text":{"type":"plain_text","text":"Cancel","emoji":true},
        "value":"click_me_123"
      }
    }
  ]
}
```

**Comment by chrishulton** [comment]
In case anyone else stumbles across this and is wondering about the message format, the `blocks` parameter refers to the blocks array, ex:

```
blocks = [
  {
    "type": "section",
    "text": {
      "type": "plain_text",
      "text": "This is a plain text section block.",
    }
  },
  {
    "type": "section",
    "text": {
      "type": "plain_text",
      "text": "This is a plain text section block.",
    }
  }
]

notifier.post(blocks: blocks)
```
