### ISSUE TITLE
Usernames with spaces

### ISSUE THREAD

**Issue by cimm** [stevenosloan/slack-notifier#114]
We are using the `at` param to mention a Slack user when posting messages:

```ruby
notifier.post text: "hello", at: "waldo"
```

This works fine for "waldo" and "jane9" but doesn't work for usernames with spaces, like "john doe" . Instead of the usual blue linked user we get `<@jane doe> hello`. I tried replacing the username with the user id but that doesn't help `@afgm13lm hello`.

Here is how it looks in Slack:

![](https://user-images.githubusercontent.com/68112/71348732-7f8f9280-256d-11ea-9549-9eb48d7467ea.png)

How can I mention a user with a space in their username?

**Comment by timothyjosefik** [comment]
I was having the same problem. If you are using .post then don't add the @.

In your example it would be
`notifier.post text: "hello", at: "afgm13lm"`

If you are using .ping it is a bit different. In that scenario you need to surround it with `<>`
So using your example again it would be
`notifier.ping "<@afgm13lm> hello"`

**Comment by cimm** [comment]
Thanks for the help but I doesn't seem to work. I tried a bunch of different versions and none seem to work. All these show the user in plain text instead of the highlighted Slack username.

```ruby
notifier.post text: "hello", at: "jane doe"
notifier.post text: "hello", at: "<@jane doe>"
notifier.post text: "hello", at: "<jane doe>"
notifier.post text: "hello", at: "@afgm13lm"
notifier.post text: "hello", at: "afgm13lm"
notifier.ping "<@jane doe> hello"
notifier.ping "<jane doe> hello"
notifier.ping "<afgm13lm> hello"
notifier.ping "<@afgm13lm> hello"
```

**Comment by cimm** [comment]
Aha, I was doing to lowercase on the userID! :man_facepalming: It works with the Slack userID when I **don't** lowercase the string.
