### ISSUE TITLE
Ruby 2.7 deprecation warnings

### ISSUE THREAD

**Issue by nburt** [stevenosloan/slack-notifier#115]
We just upgraded to Ruby 2.7 and are seeing some deprecation warnings:

```
/Users/nateburt/.rvm/gems/ruby-2.7.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/link_formatter.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/nateburt/.rvm/gems/ruby-2.7.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/link_formatter.rb:38: warning: The called method `initialize' is defined here
```

I've also noticed that there hasn't been any new commits since 2018, is this library still maintained or should we switch to https://github.com/slack-ruby/slack-ruby-client?

**Comment by stevenosloan** [comment]
resolved with https://github.com/stevenosloan/slack-notifier/pull/123
