### ISSUE TITLE
Ruby 3.0.0, LinkFormatter, positional/keyword/default arguments issue on #initialize

### ISSUE THREAD

**Issue by matthewkrom** [stevenosloan/slack-notifier#124]
The last code update for this repo is from Sept 2018, and it looks like at least one method does not support the Ruby 3.0.0 changes to keyword/positioned/default arguments, as shown below.  Using #ping on the Notifier results in an ArgumentError in the LinkFormatter.  

Is this still an active project, or has the team moved on to a different gem for Ruby 3?

```
module Slack
  class Notifier
    module Util
      class LinkFormatter

        def initialize string, formats: %i[html markdown]
          @formats = formats
          @orig    = string.respond_to?(:scrub) ? string.scrub : string
        end
      end
   end
  end
end

```

**Comment by matthewkrom** [comment]
I've monkey-patched for the very short term, using the initializer below, which tests fine in my (possibly limited) use case. Could someone more familiar with the project report on whether the code base overall should/could support Ruby 3.0.0?

```
module Slack
  class Notifier
    module Util
      class LinkFormatter

        # Outmoded for Ruby 3.0.0
        # def initialize string, formats: %i[html markdown]
        #   @formats = formats
        #   @orig    = string.respond_to?(:scrub) ? string.scrub : string
        # end
        
        # Monkey patch for Ruby 3.0.0
        def initialize string, in_opts={formats: %i[html markdown]}
          opts = in_opts || {}
          @formats = opts[:formats]
          @orig    = string.respond_to?(:scrub) ? string.scrub : string
        end
        
      end
    end
  end
end
```

**Comment by matthutchinson** [comment]
I have this same issue, your patch worked for me, would be nice to see this fixed in the gem.

**Comment by matthutchinson** [comment]
Actually I think this handles the case where you don't pass any format argument

        def initialize string, in_opts = { formats: nil }
          opts = in_opts || {}
          @formats = opts[:formats] || %i[html markdown]
          @orig    = string.respond_to?(:scrub) ? string.scrub : string
        end

right now calling `Slack::Notifier::Util::LinkFormatter.format("some message")` and your patch fails with a nil error

**Comment by punitcse** [comment]
PR https://github.com/stevenosloan/slack-notifier/pull/123 should solve the issue once merged.

**Comment by cameronbarker** [comment]
👍

**Comment by stevenosloan** [comment]
https://github.com/stevenosloan/slack-notifier/pull/123 was merged and a new version cut, so this should be resolved.
