### ISSUE TITLE
Could you add default timeout?

### ISSUE THREAD

**Issue by xiaoronglv** [stevenosloan/slack-notifier#17]
Hi @stevenosloan ,

slack-notifier is a wonderful gem. I use it to send notification in [exception_notification](https://github.com/smartinez87/exception_notification) (a  rails / sidekiq error monitor).

Sending message is a slow IO operation which will block our App. Sometime it will frozen sidekiq worker.

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-workers

Could you add default timeout to avoid frozen sidekiq/rails thread?

**Comment by stevenosloan** [comment]
Yeah, that'd be a great inclusion to the [DefaultHTTPClient](https://github.com/stevenosloan/slack-notifier/blob/master/lib/slack-notifier/default_http_client.rb). I'll take a look when I get a little more time later this week.

In the mean time, you could roll your own [injecting your own HTTP client](https://github.com/stevenosloan/slack-notifier#custom-http-client) if needed, or PR's are more than welcome.

cheers,
steven

**Comment by stevenosloan** [comment]
Hey @xiaoronglv, I just pushed out version 1.1.0 that includes the option to set http options like `open_timeout`. You can set that at either initialization for when you call ping.

```ruby
# on initialization
notifier = Slack::Notifier.new "WEBHOOK_URL", username: "foo", http_options: { open_timeout: 10 }

# or ping
notifier.ping "hello", http_options: { open_timeout: 10 }
```

**Comment by xiaoronglv** [comment]
Thanks.

:+1:
