### ISSUE TITLE
Warn if initializing with the old method signature

### ISSUE THREAD

**Issue by jayroh** [stevenosloan/slack-notifier#18]
Hey Steven!

I was just bit by a little something. I (finally) got around to updating some gems and when I rolled out my changes to our staging app we started seeing the following exception - `TypeError: no implicit conversion of Symbol into String` with the following stack-trace:

```
[GEM_ROOT]/gems/slack-notifier-1.0.0/lib/slack-notifier.rb:14 :in `delete`
[GEM_ROOT]/gems/slack-notifier-1.0.0/lib/slack-notifier.rb:14 :in `initialize`
```

Because I replace `Slack::Notifier` with a custom `FakeSlack::Notifier` in our test environment ... my tests never caught this. I was baffled until I looked the slack-notifier source and noticed the initializer's method signature changed.

Now, this is just fine, but I'm thinking a warning to people passing in two strings (the old way) would be SUPER valuable. I would have noticed this earlier. If you're cool with it I'd be more than happy to submit a PR for this. 

Thoughts?

**Comment by stevenosloan** [comment]
Yeah I think giving something more useful would be helpful. Sorry you got bit by that, this is an unfortunate case where going from `0.x.x` to `1.0.x` doesn't really capture this type of change.

A PR would be great. Are you thinking of supporting both signatures or just a warning? I feel like raising a custom exception for that (with a helpful message pointing to the [docs](https://github.com/stevenosloan/slack-notifier/blob/master/docs/upgrade-from-0.6.1.md)) would be the best path forward. That seem right to you?

**Comment by jayroh** [comment]
I was leaning towards just a warning but if the old signature works (does it? I have a hunch it does?) then I *might* play with that a little bit. The options are

1. Detect 2 strings being passed. -> `Kernel.warn "Message with link to the docs w/updated signature info."`
2. Detect 2 strings -> use old strategy -> `Kernel.warn` with info on the new strategy / link.

I'm leaning towards option 1 because adding the complexity w/2 is a bit of a short investment.

**Comment by stevenosloan** [comment]
Yeah, I definitely agree that supporting the old signature is a bit much at this point. I might lean towards raising vs. warning as it'll end up hitting an exception anyway.

**Comment by jayroh** [comment]
Noted! I'll get some code together sometime over the next few days and
we'll go from ther.

**Comment by stevenosloan** [comment]
Sounds good, thanks @jayroh

**Comment by stevenosloan** [comment]
Think I've let this one slip on by for long enough I'm going to go ahead and close it up 😬
