### ISSUE TITLE
Would be nice to prepend the hash to channel name

### ISSUE THREAD

**Issue by treeder** [stevenosloan/slack-notifier#20]
I was getting 500 errors back from slack API with no clue about why (shame on you slack) and it turns out it was because I didn't have the hash prepended to the channel. Would be nice if slack-notifier did it for you if it doesn't see a hash. 

```
notifier.channel  = "\##{channel}"
```

**Comment by stevenosloan** [comment]
That *was* actually a feature back in the [begining](https://github.com/stevenosloan/slack-notifier/issues/5), but had to be removed to allow sending to individual users or private rooms. See #7 and #8 for more information.
