### ISSUE TITLE
Dummy client in development

### ISSUE THREAD

**Issue by monkbroc** [stevenosloan/slack-notifier#22]
Hi,

I only want to send events to Slack in production, not in development.

I was thinking of creating a Slack::DummyNotifier that implements the same methods as Slack::Notifier all as no-ops.

Would you consider pulling this into the gem if I send a pull request?

Any other way you are using to avoid flooding Slack while developing?

**Comment by stevenosloan** [comment]
Personally I pass in a dummy http client, it just needs to accept `::post`. Then you can check/log/ignore any of the actual posting to slack. A no-op example:

```ruby
module NoOpHTTPClient
  def self.post uri, params={}
  end
end

notifier = Slack::Notifier.new 'WEBHOOK_URL', http_client: NoOpHTTPClient
```

**Comment by monkbroc** [comment]
OK. Both ways accomplish the same goal.

It would be great to have that in the README. I was looking in there for a recommended way to ignore requests in development.

Adding what you wrote under the Custom HTTP Client section would be sufficient: "For example to send events to Slack in production, not in development, create a dummy http client. Then you can check/log/ignore any of the actual posting to Slack. A no-op example: ..."

Thanks.

**Comment by stevenosloan** [comment]
Ah yeah, more accurately I should have said "Personally I would...", I hadn't actually thought of this case.

Added a note to the readme, thanks!

**Comment by monkbroc** [comment]
:+1: Thanks Steven
