### ISSUE TITLE
`rescue in split': bad URI(is not URI?)

### ISSUE THREAD

**Issue by korabh** [stevenosloan/slack-notifier#30]
@stevenosloan Using Hash values in initialize Slack::Notifier.new return this error 

/Users/**/.rbenv/versions/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:17:in `rescue in split': bad URI(is not URI?):  (URI::InvalidURIError)
	from /Users/**/.rbenv/versions/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:14:in `split'
	from /Users/**/.rbenv/versions/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	from /Users/**/.rbenv/versions/2.2.1/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	from /Users/**/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/slack-notifier-1.2.1/lib/slack-notifier.rb:13:in `initialize'

**Comment by stevenosloan** [comment]
Are you passing it the webhook url?

Initialization w/ hash defaults should look like this:
```ruby
Slack::Notifier.new "WEBHOOK_URL", channel: '#default',
                                   username: 'notifier'
```

**Comment by korabh** [comment]
It works when I use it as "WEBHOOK_URL" but trying to fetch same url from hash like params[:webhook] throw `rescue in split': bad URI(is not URI?): (URI::InvalidURIError)

**Comment by stevenosloan** [comment]
Hmm, I guess I'm confused on what you're trying to do. When initialized you're required to pass the webhook url as the first parameter.

Can you explain your case a little further? (examples & reasoning why you're calling it that way)

**Comment by korabh** [comment]
Well, I'm trying to fetch from .yml file a list of config eg.
slack:
  hook: "https://hooks.slack.com/services/URL"
  channel: "#channel"
  username: "username"

Then using this config file we convert it to hash like  
params = {:hook=>"https://hooks.slack.com/services/**", :channel=>"#channel", :username=>"webhook"} 
we pass params on initialize method 
Slack::Notifier.new params[:hook], channel: params[:channel],
                                   username: params[:username]  

So doing this way throw  `rescue in split': bad URI(is not URI?): (URI::InvalidURIError)

**Comment by stevenosloan** [comment]
That should definitely work. One thing with `URI#parse` is that it's error messages are super non-descriptive -- so I'm thinking *maybe* you're actually passing in a nil value.

How are you loading the yaml file? w/ standard lib the keys are going to be strings so you may actually end up with a hash like:
```ruby
params = {"hook"=>"https://hooks.slack.com/services/T04K..", "channel"=>"#channel", "username"=>"webhook"}

# although w/ that yaml snippet it'd be
{ "slack" => { "hook" => "..." } }
```

And then need to access it like so:
```ruby
Slack::Notifier.new params["hook"] # etc
```

But that's just a guess based on things I've been bit by before in the past. If that's not it, I'd check to make sure that `params[:hook]` is returning your webhook url. Then see if the URI stdlib can parse it `URI.parse(params[:hook])`

**Comment by korabh** [comment]
I thought it might be this but then I inspect this class and it return correct values.
``` ruby 
#<Weebo::Slacky:0x007f9b39b98148 @slack=#<Slack::Notifier:0x007f9b39b98120 @endpoint=#<URI::HTTPS https://hooks.slack.com/services/T04K...>, @default_payload={:channel=>"#channel", :username=>"webhook"}>>
```

**Comment by stevenosloan** [comment]
Looks like your `Weebo::Slacky` instance has a properly initialized `Slack::Notifier` instance -- where is it failing?

**Comment by korabh** [comment]
Got it, Thank you.

**Comment by sunsheeppoplar** [comment]
I'm having this issue while running an unrelated RSpec test... I'll report back if there's anything substantial

**Comment by sunsheeppoplar** [comment]
Turns out my `devise.rb` initializer was trying to run in the test environment where the key for that doesn't exist...
