### ISSUE TITLE
Is sending on unfurl_links: true possible?

### ISSUE THREAD

**Issue by sillygwailo** [stevenosloan/slack-notifier#32]
I have an issue over at Huginn, where I want to send `unfurl_links: true` over with a payload, but I wonder if it's possible at all with the `slack-notifier` gem?

(My issue with Huggin is at https://github.com/cantino/huginn/issues/892 )

**Comment by stevenosloan** [comment]
Yeah it's definitely possible. It's passed along like any of the other option:

```ruby
notifier.ping "http://eepurl.com/bsIhuX", unfurl_media: true, unfurl_links: true
```

From testing though it does look like it's a bit inconsistent, especially if you've posted the same link recently it won't unfurl.

**Comment by sillygwailo** [comment]
Looks like it does work. I have a pull request in with Huginn that adds `unfurl_links` to the options it sends to `slack-notifier`. Thanks!
