### ISSUE TITLE
Make the gem terminology consistent with the Slack API

### ISSUE THREAD

**Issue by MrPowers** [stevenosloan/slack-notifier#34]
Would you be willing to make the gem terminology consistent with the Slack API.  For example, the gem uses "channel" and "username", but the API uses "channel_name" and "user_name" (the Slack POST response uses this terminology at least: https://api.slack.com/slash-commands).  Do you think the terminology should be consistent?  Would the change have to be backwards compatible?

**Comment by stevenosloan** [comment]
I would be up to it, but we're following Slack's conventions for the [webhooks](https://api.slack.com/incoming-webhooks) which are `channel` and `username`. Funny that they're inconsistent w/ those though.
