### ISSUE TITLE
Is it possible to send a message to multiple channels at once?

### ISSUE THREAD

**Issue by martijnrusschen** [stevenosloan/slack-notifier#40]
Not sure if this is supported or not, but would like to send a message to multiple channels at once.

**Comment by stevenosloan** [comment]
I don't think that it is, at least with just a single call to slack. (if there is a way w/ the slack api I'm happy to make any necessary adjustments to support it)

Depending on your requirements you'd probably want to do this in forked processes with some kind of error handling, but pinging while iterating over the channels you want would get close.
```ruby
message = 'Hello World'
options = {}

[ '#foo', '#bar' ].each do |c|
  notifier.ping message, options.merge(channel: c)
end
```

**Comment by stevenosloan** [comment]
@martijnrusschen did that answer your question ok?

**Comment by martijnrusschen** [comment]
Thanks for answering the question. I guess this isn't supported at all by the API. Will let you know if I see something different.

**Comment by greg-moovel** [comment]
This would be a convenient feature, I'm on a DevOps team, and we frequently have to bounce into 3-5 channels to give me a head's up on updates/potential outages.

**Comment by Anki-Jane** [comment]
Ditto, for releases we are always having to paste to multiple channels.

**Comment by PavelStryhelski** [comment]
Can it updated in such a way:
if slackSend channel: contains comma separated addresses, first of all split addresses in a [] and then just perform .each for every channel?

**Comment by stevenosloan** [comment]
You can do this now with version [2.3.0](https://rubygems.org/gems/slack-notifier/versions/2.3.0) by passing an array of channels to the `:channel` param. For example:

```ruby
notifier.post text: "hello", channel: ["#general", "#random"]
# => posts 'hello' to the general & random channel
```

**Comment by oishika** [comment]
@stevenosloan how would you use that for a bunch of private channels? and can you post images as well or does it always have to be text?

**Comment by stevenosloan** [comment]
You'd specific private channels just the same, they just don't have the `#` before their name. Images, attachments, etc work the same as any other message. To post a gif for example:

```ruby
notifier.post text: "hello https://media.giphy.com/media/LfCt1sR1VweBy/giphy.gif", channels: ["#general", "private"]
```

And it will appear like

| screenshot |
| ---- |
| <img width="637" alt="screen shot 2017-08-12 at 2 59 49 pm" src="https://user-images.githubusercontent.com/868115/29243530-f0a230e2-7f6e-11e7-95db-1dda844767b5.png"> |

**Comment by siliang625** [comment]
Hello, just wondering is this feature supported in python?

**Comment by stevenosloan** [comment]
@siliang625 I think that will depend on how you're using slack in python (which library, apis, etc)

**Comment by ramielian** [comment]
https://gist.github.com/ramielian/64e7f27630d66e9c9ad163cfbf11edcb

**Comment by siegy22** [comment]
@ramielian What's your point with your php script? 😄 
This is a ruby library which makes interacting with the slack API easier (~about what your `slackService` function does).
