### ISSUE TITLE
JIRA ticket channel.

### ISSUE THREAD

**Issue by bhushangahire** [stevenosloan/slack-notifier#45]
Does anyone know if there is channel available for JIRA to create tickets if we get exception ?

**Comment by stevenosloan** [comment]
Hey @bhushangahire seems like this [integration from zapier](https://zapier.com/zapbook/zaps/2415/add-new-slack-messages-to-jira-as-new-issues/) (albiet not free) is the easiest way to get that going. From what I could tell the official integration is JIRA => Slack only.

**Comment by stevenosloan** [comment]
@bhushangahire going to go ahead and close this as I think it's answered. Feel free to open back up if not.
