### ISSUE TITLE
2.0.x Roadmap

### ISSUE THREAD

**Issue by stevenosloan** [stevenosloan/slack-notifier#46]
Hi Users. Y'all have been fantastic, truely. This Gem is now at over 1 million downloads thanks to you -- and I'm shocked. I never expected this pet project to create such a buzz. I guess other people appreciated a simple interface to just send a message to slack.

With some recent issues I'm seeing a common thread of changes necessary that I believe will lead to the 2.x version of the library, but I want to start to develop these changes out in the open. I don't have too many initial features in mind, but would like to change the interface a bit to make it more flexible for the future. Any issues/features you'd like addressed would be fantastic to hear about.
### New Interface (not too different)

``` ruby
notifier = Slack::Notifier.new ENV['WEBHOOK_URL', message: MESSAGE_DEFAULTS, link_formatter: LINK_FORMATTER_DEFAULTS, etc
notifier.ping "The message text", options={ message: CURRENT_ARGS, ARGS_FOR_MIDDLEWARE }
```

Currently options could contain any number of things (channel, username, icon_emoji, etc) -- things that may pertain to the message, or may not (`http_options`). In the future any message defaults will go under the key `:message`, so other keys can be used for other options.

I would also like to think of the `LinkFormatter` more as middleware. There's nothing particularly special about the  way it modifies messages, so to fill cases like those from @technicalpickles -- making it more extensible seems like a good option to me.

A look at how that might work:

``` ruby
class PlainLinkFormatter < Slack::Notifier::Middleware
  register :plain_link

  def format message
    # do the stuff
  end
end

notifier.ping 'the message', format: [:markdown, :plain_link]
```

This shows creating a new middleware, registering it with a name, and then using it for a message. I'd like to think of a way to "add" a single middleware to a message that isn't necessarily in a default -- but that may come later.

That's about it for my initial thinking -- I'd love to hear any feedback. The work should start relatively soon on a branch 2.0.x.

cheers,
steven

**Comment by Elektron1c97** [comment]
What about the availability to pass a boolean to set if the attachment's text should be formatted or not.
According to [this code](https://github.com/stevenosloan/slack-notifier/blob/master/lib/slack-notifier.rb#L22-L28), this can't be done.

**Comment by stevenosloan** [comment]
Yeah, good call, thats definitely something I'd like to be configurable.

**Comment by Elektron1c97** [comment]
I think the "Hack" [right here](https://github.com/stevenosloan/slack-notifier/blob/master/lib/slack-notifier.rb#L18-L20) should be improved. It's very hard to add some flags like I suggested. Because the payload param (passed to `Slack::Notifier::PayloadMiddleware::Legacy#call`) has 2 different structures depending on the passed values in `Slack::Notifier#ping`.
E.g. 
with a message:

```ruby
notifier.ping "my awesome message", attachments: [{ color: "#000", text: "awesome attachment" }]

# => { text: "my awesome message", attachments: [{color: "#000", text: "awesome attachment"}] }
```

without a message:
```ruby
notifier.ping { color: "#000", text: "awesome attachment" }

# => { color: "#000", text: "awesome attachment" }
```

I think the call without a message should return one of these:
```ruby
{text: nil, attachments: { color: "#000", text: "awesome attachment"} }
{text: "", attachments: { color: "#000", text: "awesome attachment"} }
{attachments: { color: "#000", text: "awesome attachment"} }
```

I don't know the exact API of Slack. So what do you think is the best way?

**Comment by stevenosloan** [comment]
Yeah definitely. As soon as I wrote that I've been thinking of releasing a final `1.x` release that includes the "argument assignment dance" (whatever that's properly called) and tosses out a depreciation warning it two args are passed. Have it use the legacy middleware out of the box, so should show the same behavior as 1.5.1; allow for adding additional middleware if desired; and hint at moving to whatever the new interface needs to be.

That said -- for myself and others following along -- I'd like to restate the goals of the `2.x` update:
- make the notifier more flexible for user's current (and future) use cases
- maintain the original goal of "the dang simplest way to send a message to slack"

Since my original post I've been thinking of the interface in a different way, primarily driven by the question of whether the middleware stack would changing often enough to justify having it configurable on every `#ping`. My gut says no, that you'd configure it for a specific use case -- then reuse the same notifier on each ping.

So, a rundown of what I'm thinkin now (with the supporting psuedo code):

**1)** add a `#post` method that contains all the configurable code. it accepts a single parameter, the payload.

```ruby
def post payload={}
  client.post payload: middleware.call( default_payload.merge(payload) ).to_json
end
```

**2)** `#ping` gets simplified and only accepts a single param, the message. it's just a convenience wrapper around `#post`. (makes the assumption, if you're taking the time to configure things -- you probably can live with putting the message in the `:text` key)

```ruby
def ping message
  post text: message
end
```

**3)** the default_payload, http_client, and middleware_stack are configured on initialization

```ruby
# like the current defaults
notifier = Slack::Notifier.new ENV['SLACK_URL'] do
  defaults channel:  '#general',
           username: 'notifier'
end

# with a bit of configuration
notifier = Slack::Notifier.new ENV['SLACK_URL'] do

  client DefaultHTTPClient.new( timeout: 5 )

  defaults channel:  '#general',
           username: 'notifier'

  middleware message_formatter: {
                markdown: true,
                plain_links: false
             },
             attachment_formatter: {
                wrap_array: true,
                markdown: true,
                plain_links: false
             }

end
```

For the middleware, it's hash with key `name_of_middleware` and value of `{options: hash}`

So @Elektron1c97, for your specific case of wanting to skip processing the text in attachments -- w/ a little tweak to the currently written `:legacy` middleware:

```ruby
# pseudo code rewrite to legacy.rb
class Legacy < Base
  attr_reader :opts

  def initialize opts={}
    @opts = opts
  end

  def call payload={}
    unless opts[:format_attachments] == false # addmitedly checking for false is nasty
      # do the array_wrap & attachment formatting
    end

    # rest of stuff

    return payload
  end
end

# your notifier code
notifier = Slack::Notifier.new ENV['SLACK_URL'] do
  defaults channel:  '#general',
           username: 'notifier'

  middleware legacy: { format_attachments: false }
end

notifier.post attachments: [{ text: '[not formatted](http://example.com)' }]
# => post message to slack with an attachment that looks like:
# || [not formatted](http://example.com)
```

Thanks for taking the time to review & consider, does that all make sense / sound good to you?

**Comment by Elektron1c97** [comment]
This sound perfect!

I like the configure block :heart_eyes:.
The idea of having a `post` method with only a hash as an argument makes it much more easier to handle the flags and everything!
The "argument assignment dance" with deprecation warning is :ok_hand: !

If you have something I can help with, just ask.

Cheers :beers:
