### ISSUE TITLE
Does this support receiving messages?

### ISSUE THREAD

**Issue by barmstrong** [stevenosloan/slack-notifier#49]
e.g. creating a bot etc

if not, any reason why it couldn't be added? i believe the webhook url supports this

**Comment by stevenosloan** [comment]
It does not -- and reasons for it not to would be complexity I guess.

Maybe you could describe your use case a bit more though? To support receiving the messages we'd need to have a small web stack (at minimum a little rack app, if not Roda or Sinatra) to take in the messages and then hand off to whatever is handling the commands. By that point I would think that it'd be better to defer to the user's existing stack *or* suggest using a dedicated bot project like [Lita](http://docs.lita.io/).

**Comment by sethherr** [comment]
Ok. So I made something to actually accept a url (using this gem).

It isn't generalized yet, it only works for github labels on issues on pull requests, but it will expand. Also, it's open source so if you want to add something please do! https://github.com/Reliefwatch/slack-reconciler

**Comment by stevenosloan** [comment]
@barmstrong going to close, I think this is answered. Feel free to open again.
