### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by knagode** [stevenosloan/slack-notifier#51]
Is it possible to send direct message as well with slack-notifier?

**Comment by stevenosloan** [comment]
Yep! Just set the channel name w/ `@` before the username. For example to notify me:

```ruby
notifier.ping "ohaiii", channel: "@stevenosloan"
```

**Comment by knagode** [comment]
wow. Awesome. Thanks!

**Comment by ranle** [comment]
Ok, figured it out.
Each user has a unique `member id`. 
Sending the message to `@member-id` works.
Sending it to `@username` does not work anymore.

See image.
![image](https://user-images.githubusercontent.com/6637082/44310840-9c4e1000-a3e5-11e8-8378-6e8ee5e030fb.png)

**Comment by siegy22** [comment]
I can agree on the statement from @ranle, apparently with users which exist since beginning of 2017 or earlier, it works with the display name. With newer ones it doesn't work anymore.

**Comment by stevenosloan** [comment]
Added a quick summary to the `channel` docs https://github.com/stevenosloan/slack-notifier/commit/4bf6582663dc9e5070afe3fdc42d67c14a513354, please PR if that's unclear or missing anything 😅

**Comment by siegy22** [comment]
Thanks! @stevenosloan

**Comment by leandropessoa30** [comment]
@stevenosloan 
Incredible, it would be even better if it were possible to read slack messages.

Thanks for sharing!

**Comment by krsyoung** [comment]
Hi folks, thanks for documenting this update.  Very helpful!

One clarification, when I created my Incoming Webhook I had to specify the channel it posts to.  So when I try the above, no matter what uid I reference it posts to `#general`.  @ranle did you do something special to create a webhook that can DM any user?
