### ISSUE TITLE
Async call

### ISSUE THREAD

**Issue by michaelimstepf** [stevenosloan/slack-notifier#54]
We send slack messages when our users create a booking and don't want the messaging blocking the booking process.

Would an [async call](https://github.com/TidyMe/slack-notifier/commit/d2894db5437974e165e51c11cc63f0177472c402) make sense for this gem? If yes, I can open a pull request.

**Comment by Elektron1c97** [comment]
I would implement it like this:

```ruby
  def ping_async message, options={}
    Thread.new do
      yield ping(message, options) if block_given?
    end.run
  end
```

But anyway a good point.. but I don't know if it's necessary.

**Comment by stevenosloan** [comment]
Thanks @Elektron1c97, another option would be to build an async http client, or send it to a background worker (if you have one, see: https://github.com/stevenosloan/slack-notifier/issues/50#issuecomment-167714843). My general feeling is to keep async pinging out of the core lib since the best way to handle it can vary so much application to application.

**Comment by michaelimstepf** [comment]
Thanks guys, let me know what the final decision on this is. The idea came to me after I used this [async method](https://github.com/codelittinc/slacked#to-send-an-async-message-to-slack-use-the-method).

As I mentioned before, for us it's useful as the booking form already takes a long time to process and we don't want any further hold ups. Background workers are an option but a bit heavy handed for this I find. Our backend analytics (Segment) uses the same async strategy.

**Comment by Elektron1c97** [comment]
as @stevenosloan said it's not needed in the core lib..
But if you want it like this anyway you can make your own patch for this :grin:

Or just create an async job or an async http client. (Relatively easy)

**Comment by michaelimstepf** [comment]
Cool, will patch then. Thanks

**Comment by stevenosloan** [comment]
I fully support freedom patching in this situation :)

Thanks guys
