### ISSUE TITLE
File upload to Slack channel?

### ISSUE THREAD

**Issue by ZombieHarvester** [stevenosloan/slack-notifier#57]
Hi there! Thanks for the awesome gem!

Is it possible to send a file to a Slack channel? Seems their api allows that: https://api.slack.com/methods/files.upload

**Comment by stevenosloan** [comment]
It doesn't look like it's possible with the webhooks (which is how this gem works), so you'd need to use a client that uses the web api ([slack-ruby-client](https://github.com/dblock/slack-ruby-client) or one of the other [community projects](https://api.slack.com/community#ruby))

**Comment by ZombieHarvester** [comment]
got it, thanks @stevenosloan
