### ISSUE TITLE
Message Buttons support

### ISSUE THREAD

**Issue by jschwendt** [stevenosloan/slack-notifier#58]
Any idea if someone was planning to add Message Button support?  This is a hugely valuable feature!

https://api.slack.com/docs/message-buttons

**Comment by stevenosloan** [comment]
That looks really neat -- I *think* from looking over the docs you can pass the params you'd need already. You'd just be left on your own to set up the notifier as a slack app.

I'm happy to take any PRs that would make that process more straightforward.

**Comment by aacook** [comment]
I'm also in the middle of setting this up. Not sure if the extra parameters I'm sending are being sent through. For my use case, I'm trying to pass replace_original (https://api.slack.com/docs/message-buttons#overview):
`$ notifier.ping text: text, attachments:attachments, replace_original: false`

But it looks like Slack is replacing my messages. Am I using the wrong syntax?

**Comment by stevenosloan** [comment]
@aacook that looks correct for me -- it may be I don't have an app set up so I don't have buttons actually working (just showing up), but seems to always just append another message for me:

```ruby
notifier.ping text: 'hello', attachments: [{fallback: 'hodor', callback_id: 'hodor1', actions: [{name: 'one', text: 'one', type: 'button'}]}], replace_original: false
```

If you keep running into trouble, I'd suggest checking the actual params that get posted and seeing if slack support will help you out. You can do that with a "logger" http client to dump what would have been sent:

```ruby
module LoggerClient
  def self.post uri, params={}
    STDOUT.puts "uri: #{uri}"
    STDOUT.puts "params: #{params}"
  end
end

notifier = Slack::Notifier.new ENV['WEBHOOK_URL'], http_client: LoggerClient
notifier.ping "hello"
# => uri: XXX
# => {:payload => '{"text":"hello"}'}
```

**Comment by aacook** [comment]
Thanks, appreciate it. Turns out it wasn't working for an unrelated reason. Everything's running beautifully now.

**Comment by stevenosloan** [comment]
Awesome!
