### ISSUE TITLE
Is there a way to ping multiple channels?

### ISSUE THREAD

**Issue by kmuthupa** [stevenosloan/slack-notifier#62]
Does the API currently support pinging multiple channels with the same message?

**Comment by Elektron1c97** [comment]
I can't find something like that in the API documentation. I think you need to do it that way at the moment:

```ruby
notifier = Slack::Notifier.new "WEBHOOK_URL"
%w(general random).each do |channel|
  notifier.ping("message", channel: channel)
end
```

**Comment by kmuthupa** [comment]
I figured after I looked at the API. I ll stick to doing multiple pings for now. Thanks anyway!
