### ISSUE TITLE
Send snippet using Slack API

### ISSUE THREAD

**Issue by Erowlin** [stevenosloan/slack-notifier#63]
Hi, 

Not really an issue, but is it possible to create a message including a snippet from the API using a specific markup ? I cannot see anything related in Slack documentation. 

Thanks.

**Comment by stevenosloan** [comment]
mmmm, yeah I couldn't find anything documentation wise for that either. I'd imagine it's some special formatting for attachments, but don't have anything to really back up that idea.

If you could hit up https://slack-notifier.slack.com/help/requests/new (they've been super nice for me in the past) to get some info, that'd be awesome. I'm happy to make any changes to the lib necessary to make the call possible/easy.

**Comment by Erowlin** [comment]
Thank you for the feedback. 

I will send them a message and let you know if I have some news.

**Comment by Erowlin** [comment]
Some news, here is the answer from Slack

> Hi Thomas,
> 
> Thanks for your message! Sure, you can use Slack's API to upload snippets to channels. Snippets can be created using the files.upload method. You can define the type of file with filetype identifier: we support Ruby.
> 
> You can find relevant links to our documentation below: https://api.slack.com/methods/files.upload https://api.slack.com/types/file#file_types
> 
> Don't hesitate to get back to me with further questions.
> 
> Best, Wojtek.
> 

I believe they are not gonna support snippet upload using markup - and that's sound normal for me since it involves uploading a file.

**Comment by Erowlin** [comment]
Another response from the Slack team : 

> You could build an integration that creates snippet upon a message from a user but this will still need to call the files.upload method in the end.
> 
> For instance, you could build a slash command that sends a message to an intermediary point in your end which then calls files.upload, passing your message as the content of the snippet.
> 
> The same can be achieved with an Outgoing Webhook or our Events API.

**Comment by stevenosloan** [comment]
Hey @Erowlin thanks for tracking that down.

Unfortunately I do think it ends up being a bit out of scope. While it'd be great and would fit into the philosophy of being "the simplest way to post to slack", adding (or changing) to use the full web api vs. webhooks interface would be a bit much. That's more in the realm of [full featured api clients](https://github.com/slack-ruby/slack-ruby-client#web-client).

**Comment by Erowlin** [comment]
Ok, thanks for your answer !
