### ISSUE TITLE
adding attachments into messages

### ISSUE THREAD

**Issue by alonhartal** [stevenosloan/slack-notifier#67]
https://api.slack.com/methods/files.upload

**Comment by stevenosloan** [comment]
@alonhartal do you mind expanding on what your question/proposal is? (it's possible https://github.com/stevenosloan/slack-notifier/issues/57 addresses it)

**Comment by pfletch1023** [comment]
Any plans to re-open this issue? Would really appreciate ability to include a file attachment.

**Comment by stevenosloan** [comment]
@pfletch1023 unless slack starts supporting file uploads through [incoming webhooks](https://api.slack.com/incoming-webhooks) (the method this gem uses to communicate with slack) I don't believe so.
