### ISSUE TITLE
Passing array into ping has some weird side effects

### ISSUE THREAD

**Issue by llamicron** [stevenosloan/slack-notifier#71]
First off, I have added on to the ping method. Here's my `ping` method:
```ruby
def ping(message)
    if message.is_a? Array
        final = message.join("\n")
        @slack.ping(final)
    end
    @slack.ping(message)
end
```
You can ping a string line normal, but you can pass through an array, which will format it as a string with `\n` characters. This will let you send multi line messages in slack. eg.
```ruby
ping(['line1', 'line2', 'line3'])
```
in slacks appears as:
```
line1
line2
line3
```

This runs fine, but after execution I get the following error:
```bash
NoMethodError: undefined method `gsub' for ["line1", "line2", "line3"]:Array
from /var/lib/gems/2.1.0/gems/slack-notifier-2.1.0/lib/slack-notifier/util/link_formatter.rb:42:in `sub_html_links'
```
I believe this has something to do with how `slack-notifier` parses links. I don't fully understand this, I'm not sure if this is intended behavior. The ping goes through and sends without a problem first, and then the error happens.

**Comment by stevenosloan** [comment]
Hey @llamicron, it looks like you're calling the original `#ping` twice in your method, once with the joined array and again w/ the original message.

```ruby
def ping(message)
    if message.is_a? Array
        final = message.join("\n")
        @slack.ping(final) # <= this is where the successful ping happens
    end
    @slack.ping(message) # <= this is where it then fails
end
```
It's that second call that causes the error since slack-notifier isn't designed to take an array as an argument.

**Comment by llamicron** [comment]
@stevenosloan You're absolutely right. I've since refactored that method and it works fine now. Sorry for the inconvenience.

**Comment by stevenosloan** [comment]
No worries, glad that's working for you :)
