### ISSUE TITLE
Thread support?

### ISSUE THREAD

**Issue by kcm** [stevenosloan/slack-notifier#74]
I'm trying to `post` with a `thread_ts` that I know corresponds to a thread's `ts` but it's still printed to the channel, not the thread in the channel. If I omit the `channel` parameter to the `post` call, it's not posted to the channel at all. How can I `post` a message to an existing thread?

Here's the [Slack Threading API docs](https://api.slack.com/docs/message-threading).

**Comment by kcm** [comment]
Example:

`notifier.post text: "#{response}", thread_ts: "1234.56", channel: '#foobar'`

**Comment by stevenosloan** [comment]
Unfortunately it doesn't look like the [webhook API](https://api.slack.com/incoming-webhooks) supports threads, so it's a bit out of scope of slack notifier. I'd suggest looking into one of the more full featured [slack clients](https://github.com/slack-ruby/slack-ruby-client#web-client) if you need it.

**Comment by kcm** [comment]
Confirmed with Slack that the webhook API does not currently support threads, but they are considering it for the future. Thanks.

**Comment by Startouf** [comment]
Hey, Slack says webhooks now support threading !

https://api.slack.com/messaging/webhooks#threads

I've tested it and it works with the current slack notifier

Here is some sample code

```
# Link obtained by copy-pasting the link to a message
slack_message_request = 'https://myjobglasses.slack.com/archives/DD3F2GGG4/p1583742420167800'
slack_channel = "#general" # You must add the channel or it won't work (it is also contained in the slack_message_request but as an ID and not its name)

slack.ping("Reply in thread", 
    thread_ts: slack_message_request[/[^\/p]*$/].insert(-7, '.'),
    channel: slack_channel,
)
```
