### ISSUE TITLE
is it possible notify with  image

### ISSUE THREAD

**Issue by uzaif313** [stevenosloan/slack-notifier#89]
i want to send image with `ping` method it is possible ?

**Comment by stevenosloan** [comment]
It is, you just include the url in the text field, here's an example: https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22hello%20https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FLfCt1sR1VweBy%2Fgiphy.gif%22%7D

**Comment by siegy22** [comment]
@uzaif313 if you're thinking about sending an image as an attachment, it's not possible through incoming webhooks at the moment. (see https://github.com/stevenosloan/slack-notifier/issues/57)

**Comment by stevenosloan** [comment]
Doing a little issue pruning, and seems like this is resolved 😄  — lemme know if you feel like it's not.
