### ISSUE TITLE
Is there any way to include a markdown blockquote in a message?

### ISSUE THREAD

**Issue by praxeum** [stevenosloan/slack-notifier#92]
If I just do this:

```
"This is a message: \n > #{@reply.content}"
```

The end result is

```
This is a message:
> Message
```

...but ideally I'd like that arrow to be formatted in Markdown when brought into Slack so it becomes a blockquote. Any idea how that can be done?

**Comment by stevenosloan** [comment]
Doing a little issue pruning, and seems like this is resolve 😄  — lemme know if you feel like it's not.
