### ISSUE TITLE
`split': bad URI(is not URI?): (URI::InvalidURIError)

### ISSUE THREAD

**Issue by prabs401** [stevenosloan/slack-notifier#95]
# How to solved this ?
# #`split': bad URI(is not URI?): (URI::InvalidURIError)

`require "net/https"`
`require "uri"`

`puts "input target : "`
`target = getsd`
`uri = URI.parse(target)`
`http = Net::HTTP.new(uri.host, uri.port)`
`http.use_ssl = true`

`request = Net::HTTP::Get.new(uri.request_uri)`
`res = http.request(request)`

`res.code`

**Comment by stevenosloan** [comment]
hey @prabs401 could you provide some more detail of how you're using slack-notifier to run into this? (along w/ what version)

**Comment by stevenosloan** [comment]
Doing a little issue pruning, feel free to open this back up w/ some more reproduction information when you have it.
