### ISSUE TITLE
Is the stack trace limited?

### ISSUE THREAD

**Issue by zedtux** [stevenosloan/slack-notifier#99]
It looks like I have an exception posted on a Slack channel with a limited stacktrace, so is it limited? If it is, is there an option to no more limit it and get it fully?

**Comment by stevenosloan** [comment]
Hey @zedtux could you link an example of how you're posting the exceptions? I don't think there's anything in this gem that would limit your output and that'd be very helpful to debug your issue.

**Comment by zedtux** [comment]
Hey @stevenosloan.

```ruby
class MyController < ApplicationController
  rescue_from Exception, with: :render_500

  private

  def render_500(e = nil)
    # Some treatments but not touching at all the `e` variable ...

    ExceptionNotifier.notify_exception(e, env: Rails.env, data: { message: message, group: group_name, url: request.fullpath, params: params, ip: request.remote_ip.to_s, agent: request.env['HTTP_USER_AGENT'].to_s })
  end
end
```

The problem is that slack-notifier is using the full stack, not the app stack, and in Slack only the 5 first lines are visible so that if the app stack starts after line 5, we have no idea where it come from.

We had to add the email notifier in addition to the slack one because in the email notifier we have the app stack only, which is awesome for us to fix our issue.

**Comment by stevenosloan** [comment]
It looks like the `ExceptionNotifier.` gem added support for configuring how many lines of the backtrace get passed along (https://github.com/smartinez87/exception_notification/pull/353), this is a space I'm not particularly familiar with but seems like some configuration to [`ActiveSupport::BacktraceCleaner`](http://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html) would allow reducing it to just the application stack as well.

**Comment by zedtux** [comment]
Thank you @stevenosloan for pointing me to this option that I wasn't aware of.

Just my point of view: To me it is strange that the email and the slack notifier aren't showing the same backtrace. Out-of-the-box the slack notifier looks useless because no application have zero dependencies, and a dependency trace will, almost all the time, be on top of the backtrace.
The slack notifier should show the app stack or at least provides an option to switch between the two modes.

Anyways, I will give a try to what you gave me and let you know. 👍

**Comment by zedtux** [comment]
I tried to play with `ActiveSupport::BacktraceCleaner` but this is impacting the entire application, while we want to clean the backtrace only with the slack notifier.

@stevenosloan the email notifier seem to use this to cleanup the backtrace.

**Comment by stevenosloan** [comment]
@zedtux  if you're still having trouble with this please follow up with the [ExceptionNotification](https://github.com/smartinez87/exception_notification) gem since that's where the backtrace trimming is happening not in the slack-notifier gem.
